require('dotenv').config();
const express = require('express');
const fs = require('fs');
const path = require('path');
const app = express();
app.use(express.json());
app.use(express.static('public'));
const DATA = path.join(__dirname, 'data');
const readJSON = (name, fallback) => { try { return JSON.parse(fs.readFileSync(path.join(DATA, name), 'utf8')); } catch { return fallback; } };
const writeJSON = (name, value) => fs.writeFileSync(path.join(DATA, name), JSON.stringify(value, null, 2));
function log(msg, data={}) { const logs = readJSON('logs.json', []); logs.unshift({ time: new Date().toISOString(), msg, data }); writeJSON('logs.json', logs.slice(0, 500)); }
function ema(values, len) { if (!values.length) return []; const k = 2 / (len + 1); let out = [values[0]]; for (let i = 1; i < values.length; i++) out.push(values[i] * k + out[i-1] * (1-k)); return out; }
function atr(candles, len=14) { const trs=[]; for(let i=1;i<candles.length;i++){ const h=candles[i].high,l=candles[i].low,pc=candles[i-1].close; trs.push(Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc))); } return ema(trs,len).pop()||0; }
function macd(closes) { const e12=ema(closes,12), e26=ema(closes,26); const line=e12.map((v,i)=>v-(e26[i]||v)); const signal=ema(line,9); const hist=line.map((v,i)=>v-(signal[i]||v)); const n=line.length-1; return {line:line[n]||0,prevLine:line[n-1]||0,signal:signal[n]||0,prevSignal:signal[n-1]||0,hist:hist[n]||0,prevHist:hist[n-1]||0}; }
function smi(candles, len=14, smooth=3) { const closes=candles.map(c=>c.close); let raw=[]; for(let i=0;i<candles.length;i++){ const slice=candles.slice(Math.max(0,i-len+1),i+1); const hh=Math.max(...slice.map(c=>c.high)); const ll=Math.min(...slice.map(c=>c.low)); const mid=(hh+ll)/2; const range=(hh-ll)/2||1; raw.push(((closes[i]-mid)/range)*100); } const line=ema(raw,smooth); const sig=ema(line,smooth); const n=line.length-1; return {value:line[n]||0,prevValue:line[n-1]||0,signal:sig[n]||0,prevSignal:sig[n-1]||0}; }
function structure(candles){ const recent=candles.slice(-20); if(recent.length<10)return 'NEUTRAL'; const highs=recent.map(c=>c.high), lows=recent.map(c=>c.low); const avg=a=>a.reduce((x,y)=>x+y,0)/a.length; const h1=avg(highs.slice(0,10)),h2=avg(highs.slice(10)),l1=avg(lows.slice(0,10)),l2=avg(lows.slice(10)); if(h2>h1&&l2>l1)return 'BULLISH'; if(h2<h1&&l2<l1)return 'BEARISH'; return 'NEUTRAL'; }
function cloudTouch(candles, side){ const closes=candles.map(c=>c.close); const e50=ema(closes,50), e200=ema(closes,200); const c=candles.at(-1); const top=Math.max(e50.at(-1)||c.close,e200.at(-1)||c.close); const bot=Math.min(e50.at(-1)||c.close,e200.at(-1)||c.close); const touched=c.low<=top&&c.high>=bot; if(side==='LONG')return touched&&c.close>=bot; if(side==='SHORT')return touched&&c.close<=top; return false; }
function liquiditySweep(candles, side){ const c=candles.at(-1); const prev=candles.slice(-12,-1); if(prev.length<5)return false; if(side==='LONG'){ const low=Math.min(...prev.map(x=>x.low)); return c.low<low&&c.close>low; } const high=Math.max(...prev.map(x=>x.high)); return c.high>high&&c.close<high; }
function validateSetup(candles, side){ const closes=candles.map(c=>c.close); const e5=ema(closes,5).at(-1), e12=ema(closes,12).at(-1), e50=ema(closes,50).at(-1), e200=ema(closes,200).at(-1); const m=macd(closes); const s=smi(candles); const st=structure(candles); const c=candles.at(-1); const a=atr(candles,14); const body=Math.abs(c.close-c.open); let score=0, reasons=[]; if(side==='LONG'){ if(st==='BULLISH'){score+=2; reasons.push('bullish structure');} if(e50>e200){score+=1; reasons.push('EMA50>EMA200');} if(cloudTouch(candles,'LONG')){score+=1; reasons.push('cloud touch');} else reasons.push('reject: no cloud touch'); if(s.prevValue<-40&&s.value>-40&&s.value>s.signal){score+=2; reasons.push('SMI recovered above -40');} if(m.line>m.signal&&m.hist>m.prevHist){score+=2; reasons.push('MACD bullish momentum');} if(e5>e12&&c.close>c.open){score+=2; reasons.push('KN bullish candle');} if(liquiditySweep(candles,'LONG')){score+=1; reasons.push('liquidity sweep reclaim');} } else { if(st==='BEARISH'){score+=2; reasons.push('bearish structure');} if(e50<e200){score+=1; reasons.push('EMA50<EMA200');} if(cloudTouch(candles,'SHORT')){score+=1; reasons.push('cloud touch');} else reasons.push('reject: no cloud touch'); if(s.prevValue>40&&s.value<40&&s.value<s.signal){score+=2; reasons.push('SMI rejected below +40');} if(m.line<m.signal&&m.hist<m.prevHist){score+=2; reasons.push('MACD bearish momentum');} if(e12>e5&&c.close<c.open){score+=2; reasons.push('KN bearish candle');} if(liquiditySweep(candles,'SHORT')){score+=1; reasons.push('liquidity sweep rejection');} } if(a&&(c.high-c.low)>1.5*a)reasons.push('reject: candle too large'); if(a&&body>1.0*a)reasons.push('reject: body too large'); return {score,reasons,atr:a,structure:st,macd:m,smi:s,ema:{e5,e12,e50,e200}}; }
async function fetchCandles(symbol, resolution='5m'){ try{ const now=Math.floor(Date.now()/1000); const start=now-60*5*260; const url=`https://api.delta.exchange/v2/history/candles?symbol=${symbol}&resolution=${resolution}&start=${start}&end=${now}`; const res=await fetch(url); const json=await res.json(); const rows=json.result||[]; return rows.map(r=>({time:r.time||r[0],open:Number(r.open??r[1]),high:Number(r.high??r[2]),low:Number(r.low??r[3]),close:Number(r.close??r[4]),volume:Number(r.volume??r[5]??0)})).filter(x=>Number.isFinite(x.close)).sort((a,b)=>a.time-b.time); } catch(e){ log('candle fetch failed',{symbol,error:e.message}); return []; } }
function createPaperTrade(symbol, side, candles, validation){ const trades=readJSON('trades.json',[]), positions=readJSON('positions.json',[]); const c=candles.at(-1), a=validation.atr||c.close*0.005; const entry=side==='LONG'?c.close-a*0.15:c.close+a*0.15; const sl=side==='LONG'?entry-a*1.5:entry+a*1.5; const risk=Math.abs(entry-sl); const trade={id:Date.now()+'-'+symbol,time:new Date().toISOString(),symbol,side,status:'PENDING_LIMIT',entry,sl,tp1:side==='LONG'?entry+risk:entry-risk,tp2:side==='LONG'?entry+2*risk:entry-2*risk,tp3:side==='LONG'?entry+3*risk:entry-3*risk,score:validation.score,reasons:validation.reasons,paper:true}; positions.push(trade); trades.push(trade); writeJSON('positions.json',positions); writeJSON('trades.json',trades); log('paper trade created',trade); return trade; }
async function scanOnce(){ const settings=readJSON('settings.json',{}); const positions=readJSON('positions.json',[]); const maxActive=Number(process.env.MAX_ACTIVE_TRADES||settings.maxActiveTrades||2); if(!settings.botEnabled||!settings.paperMode||settings.liveMode)return {skipped:'bot disabled or live mode blocked'}; if(positions.filter(p=>!['CLOSED','CANCELLED'].includes(p.status)).length>=maxActive)return {skipped:'max active trades reached'}; const minScore=Number(process.env.MIN_TRADE_SCORE||settings.minTradeScore||8); const results=[]; for(const symbol of settings.coins||[]){ const candles=await fetchCandles(symbol,'5m'); if(candles.length<220){results.push({symbol,skipped:'not enough candles'}); continue;} for(const side of ['LONG','SHORT']){ const v=validateSetup(candles,side); results.push({symbol,side,score:v.score,reasons:v.reasons}); if(v.score>=minScore&&!v.reasons.some(r=>r.startsWith('reject'))){ const trade=createPaperTrade(symbol,side,candles,v); return {opened:trade,results}; } } } log('scan complete - no valid trade',{count:results.length}); return {opened:null,results}; }
app.get('/api/status',(req,res)=>{ const settings=readJSON('settings.json',{}); const trades=readJSON('trades.json',[]); const positions=readJSON('positions.json',[]); const wins=trades.filter(t=>t.result==='WIN').length; const losses=trades.filter(t=>t.result==='LOSS').length; res.json({settings,tradesCount:trades.length,wins,losses,winRate:trades.length?Math.round(wins/trades.length*100):0,positions}); });
app.post('/api/scan',async(req,res)=>res.json(await scanOnce()));
app.get('/api/logs',(req,res)=>res.json(readJSON('logs.json',[])));
app.get('/api/trades',(req,res)=>res.json(readJSON('trades.json',[])));
app.get('/api/positions',(req,res)=>res.json(readJSON('positions.json',[])));
app.post('/api/emergency-stop',(req,res)=>{ const s=readJSON('settings.json',{}); s.botEnabled=false; writeJSON('settings.json',s); log('EMERGENCY STOP'); res.json({ok:true,botEnabled:false}); });
const port=process.env.PORT||3000; app.listen(port,()=>console.log(`BOT12 Light running on http://localhost:${port}`));
